name: Build Test Kernel

on:
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [A546E, A546B]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            attr golang libelf-dev dwarves rsync libbrotli-dev \
            libgtest-dev libprotobuf-dev libunwind-dev libusb-1.0-0-dev libzstd-dev libc6-dev \
            linux-modules-extra-$(uname -r) build-essential p7zip-full libarchive-tools

      - name: Fetch ToolChain
        run: |
          mkdir ~/Prebuilts
          
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 ~/Prebuilts/gl-clang
          rm -fr ~/Prebuilts/gl-clang/clang-3* ~/Prebuilts/gl-clang/clang-r4* ~/Prebuilts/gl-clang/clang-r51* ~/Prebuilts/gl-clang/.git*
          
          git clone https://android.googlesource.com/platform/prebuilts/gas/linux-x86 ~/Prebuilts/gas/linux-x86
          
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts/build-tools ~/Prebuilts/build-tools

      - name: Fetch AnyKernel3
        run: |
          git clone --branch a54x https://github.com/Vaz15k/AnyKernel3.git ~/AnyKernel3
          mkdir ~/files

      - name: Build Kernel Clean
        run: |
          source ./build_kernel.sh ${{ matrix.target }}
          cp ~/AnyKernel3/Squeak* ~/files

      - name: Upload Test Build ${{ matrix.target }}
        uses: actions/upload-artifact@v4
        with:
          name: Squeak-${{ matrix.target }}
          path: ~/files/Squeak*
